default: &default
  adapter: postgresql
  encoding: unicode
  username: dstancu
  password: 
  pool: 5
  timeout: 5000
  port: 5432

development:
  <<: *default
  database: birdfeed

production:
  <<: *default
  database: birdfeed_prod 
