default: &default
  adapter: postgresql
  encoding: unicode
  username: rails
  password: rails
  pool: 5
  timeout: 5000

development:
  <<: *default
  database: birdfeed

production:
  <<: *default
  database: birdfeed_prod