default: &default
  adapter: postgresql
  encoding: unicode
  username: rails
  password: rails
  pool: 5
  timeout: 5000

development:
  <<: *default
  database: birdfeed

production:
  adapter: postgresql
  encoding: unicode
  username: <%= ENV["PG_U"] %>
  password: <%= ENV["PG_P"] %>
  database: <%= ENV["PG_D"] %>
  pool: 5
  timeout: 5000